# Change these first
owner: the-grey-group # Your GitHub organization or username, where this repository lives
repo: datalab-status # The name of this repository
user-agent: greymon-bot
assignees: # Users to assign downtime issues (optional)
  - ml-evs

status-website:
  publish: true

sites:
  - name: Datalab API
    url: https://api.odbx.science
  - name: Datalab 
    url: https://datalab.odbx.science
  - name: Datalab API (dev)
    url: https://api-dev.odbx.science
  - name: Datalab (dev)
    url: https://datalab-dev.odbx.science
  - name: odbx
    url: https://optimade.odbx.science
