# Change these first
owner: the-grey-group # Your GitHub organization or username, where this repository lives
repo: datalab-status # The name of this repository

sites:
  - name: Datalab
    url: https://api.odbx.science
  - name: Datalab (dev)
    url: https://api-dev.odbx.science
  - name: odbx
    url: https://optimade.odbx.science
