# Change these first
owner: the-grey-group # Your GitHub organization or username, where this repository lives
repo: datalab-status # The name of this repository
user-agent: greymon-bot
assignees: # Users to assign downtime issues (optional)
  - ml-evs

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "13 * * * *"

sites:
  - name: Datalab
    url: https://api.odbx.science
    headers:
    - "Authorization: $BASIC_AUTH_HEADERS"
  - name: Datalab (dev)
    url: https://api-dev.odbx.science
    headers:
    - "Authorization: $BASIC_AUTH_HEADERS"
  - name: odbx
    url: https://optimade.odbx.science
