# Change these first
owner: the-grey-group # Your GitHub organization or username, where this repository lives
repo: datalab-status # The name of this repository
user-agent: greymon-bot
assignees: # Users to assign downtime issues (optional)
  - ml-evs

sites:
  - name: Datalab
    url: https://api.odbx.science
    headers:
    - "Authorization: $BASIC_AUTH_HEADERS"
  - name: Datalab (dev)
    url: https://api-dev.odbx.science
    headers:
    - "Authorization: $BASIC_AUTH_HEADERS"
  - name: odbx
    url: https://optimade.odbx.science
